import { MOCK_REPORT, getEvidence, type MockSection } from "./report-mock";

/**
 * 把 MockReport 渲染为 Markdown。
 * 含：title / metadata / sections / paragraphs (with evidence footnotes) / data source 附录。
 *
 * v1 客户端生成；Sprint 2 由 Reporter Agent 直接吐 markdown，前端只 download。
 */

export function renderReportAsMarkdown(
  localEdits: Record<string, string> = {},
  showV2 = false
): string {
  const lines: string[] = [];
  const r = MOCK_REPORT;

  lines.push(`# ${r.target} vs ${r.competitors.join(" · ")}`);
  lines.push("");
  lines.push(
    `> ${r.summary}`
  );
  lines.push("");
  lines.push(`**Template**: \`${r.templateId}\` · **Generated**: ${r.generatedAt}`);
  lines.push(
    `**Word count**: ${r.metadata.wordCount} · **Claims**: ${r.metadata.claimCount} · **Evidences**: ${r.metadata.evidenceCount}`
  );
  if (Object.keys(localEdits).length > 0) {
    lines.push(
      `**User edits**: ${Object.keys(localEdits).length} paragraph(s) modified (counted toward metrics.edit_rate)`
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  const allEvidenceIds = new Set<string>();

  r.sections.forEach((section) => {
    lines.push(`## ${section.number}. ${section.title}`);
    lines.push("");
    section.paragraphs.forEach((p, idx) => {
      const text = localEdits[p.id] ?? (showV2 && p.pendingV2 ? p.pendingV2.text : p.text);
      const evidenceIds =
        showV2 && p.pendingV2 ? p.pendingV2.evidenceIds : p.evidenceIds;
      const tags: string[] = [];
      if (localEdits[p.id]) tags.push("**user-edited v2**");
      else if (showV2 && p.pendingV2) tags.push("**v2 preview**");
      if (p.isSoftConclusion) tags.push("*soft conclusion*");
      if (p.isQuantitative) tags.push("*quantitative*");
      if (p.qaIssue) {
        tags.push(
          `> ⚠ QA · ${p.qaIssue.severity} · ${p.qaIssue.dimension}: ${p.qaIssue.note}`
        );
      }
      const tagLine = tags.length > 0 ? tags.join(" · ") : "";
      const refs = evidenceIds
        .map((eid) => `[^${eid}]`)
        .join("");
      lines.push(`${idx + 1}. ${text} ${refs}`.trimEnd());
      if (tagLine) {
        lines.push(`   ${tagLine}`);
      }
      lines.push("");
      evidenceIds.forEach((eid) => allEvidenceIds.add(eid));
    });
  });

  /* footnotes — evidence appendix */
  if (allEvidenceIds.size > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## 附录 · Evidence references");
    lines.push("");
    Array.from(allEvidenceIds)
      .sort()
      .forEach((eid) => {
        const ev = getEvidence(eid);
        if (!ev) return;
        lines.push(
          `[^${ev.id}]: **${ev.product}** · ${ev.sourceType} · authority ${ev.authority} · collected ${ev.collectedAt} · ${ev.sourceLabel}`
        );
        lines.push(`   > "${ev.content}"`);
        lines.push(`   <${ev.sourceUrl}>`);
        lines.push("");
      });
  }

  /* compliance disclaimer (per docs/COMPLIANCE.md § 3.3) */
  lines.push("---");
  lines.push("");
  lines.push("## 数据来源声明");
  lines.push("");
  lines.push(
    `本报告基于公开渠道于 ${r.generatedAt.slice(0, 10)} 采集的资料生成：` +
      "各产品官网首页、定价页、帮助文档（详见 Evidence 附录）、" +
      "G2 / Capterra 用户公开评价、官方博客与更新日志。"
  );
  lines.push("");
  lines.push(
    "采集遵循各站点 robots.txt 与公开服务条款；引用片段限制在合理使用范围内。"
  );
  lines.push("");
  lines.push(
    "报告中观点为基于上述资料的 AI 分析推断，**不构成投资 / 采购建议**。" +
      "每条结论可在「证据库」反向溯源到原始文本。"
  );
  lines.push("");
  lines.push(
    "_Generated by 竞品分析 Agent 协作平台 · run #03_"
  );

  return lines.join("\n");
}

/** 在浏览器中触发下载 */
export function downloadMarkdown(filename: string, content: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** 简化的 section 计数（report-layout.tsx 用） */
export function countLocalEdits(localEdits: Record<string, string>): number {
  return Object.keys(localEdits).length;
}

export { type MockSection };
